[build]
  command = "pnpm build:netlify"
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "22"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
